apiVersion: operator.aquasec.com/v1alpha1
kind: AquaCsp
metadata:
  name: aqua
spec:
  requirements: true
  password: "Password1"
  rbac:
    enable: true
    openshift: false
    privileged: true
  registry:
    url: "registry.aquasec.com"
    username: "example@gmail.com"
    password: "" # Password
    email: "example@gmail.com"
  database:
    replicas: 1
    service: "ClusterIP"
    image:
      repository: "database"
      registry: "registry.aquasec.com"
      tag: "4.0"
      pullPolicy: "IfNotPresent"
  gateway:
    replicas: 1
    service: "ClusterIP"
    image:
      repository: "gateway"
      registry: "registry.aquasec.com"
      tag: "4.0"
      pullPolicy: "IfNotPresent"
  server:
    replicas: 1
    service: "LoadBalancer"
    image:
      repository: "console"
      registry: "registry.aquasec.com"
      tag: "4.0"
      pullPolicy: "IfNotPresent"
  scanner:
    deploy:
      replicas: 1
      service: "ClusterIP"
      image:
        repository: "scanner"
        registry: "registry.aquasec.com"
        tag: "4.0"
        pullPolicy: "IfNotPresent"
    min: 1
    max: 5
    imagesPerScanner: 100
  adminPassword: "Password1"
  licenseToken: # Licence
  clustermode: false
  ssl: false
  auditSsl: false
